#!/bin/bash

set -e
D="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# This script builds a binary dpkg for Debian based distros. It does not
# currently run in CI, and is instead run manually and the resulting dpkg is
# uploaded to GitHub via the web UI.
#
# Note that this requires 'cargo deb', which can be installed with
# 'cargo install cargo-deb'.
#
# This should be run from the root of the ripgrep repo.

TARGET=''
INSTALL_ARG=''
while (( $# )); do
    case "$1" in
        --target)
            if [[ -z "$2" ]]; then
                echo >2 "Error: missing argument to --target"
                exit 1
            fi
            TARGET="$2"
            shift
            ;;
        --install)
            INSTALL_ARG='--install'
            ;;
    esac
    shift
done

if [[ -n "$TARGET" ]]; then
    TARGET_ARGS=(--target "$TARGET")
else
    TARGET_ARGS=()
fi

if ! command -V cargo-deb > /dev/null 2>&1; then
    echo "cargo-deb command missing" >&2
    exit 1
fi

if ! command -V asciidoctor > /dev/null 2>&1; then
    echo "asciidoctor command missing" >&2
    exit 1
fi

# 'cargo deb' does not seem to provide a way to specify an asset that is
# created at build time, such as ripgrep's man page. To work around this,
# we force a debug build, copy out the man page (and shell completions)
# produced from that build, put it into a predictable location and then build
# the deb, which knows where to look.
cargo check

DEPLOY_DIR=deployment/deb
OUT_DIR="$("$D"/cargo-out-dir target/debug/)"
mkdir -p "$DEPLOY_DIR"

# Copy man page and shell completions.
cp "$OUT_DIR"/{rg.1,rg.bash,rg.fish} "$DEPLOY_DIR/"
cp complete/_rg "$DEPLOY_DIR/"

version="$(git describe --tags --match='[0-9]*' --dirty=+)"

# Since we're distributing the dpkg, we don't know whether the user will have
# PCRE2 installed, so just do a static build.
PCRE2_SYS_STATIC=1 cargo deb --strip "${TARGET_ARGS[@]}" --deb-version "$version" $INSTALL_ARG
